# Schema 模块 — 圆桌会议 + 企划工作室全部输入输出契约
# 证据引用契约：所有 Agent 输出必须绑定 EvidenceRef

from .brief import Brief, BudgetRange, Weights, WeightTemplate
from .challenge import ChallengeRecord, ChallengeStance
from .evidence import Confidence, EvidenceMixin, EvidenceRef
from .feature import FeatureMatrix, TrendItem
from .gtm import CountryPlan, GTMPlan
from .ip_assessment import IPAssessment, IPCandidate
from .planning import (
    CategoryRank,
    CompetitiveMap,
    CompetitorProduct,
    ConsumerVoice,
    CostCheck,
    DataBoard,
    EvidenceLink,
    GapZone,
    HeatCurve,
    HeatCurveSeries,
    HitProduct,
    HotProductRank,
    InsightBase,
    InsightBundle,
    IPPoolItem,
    Opportunity,
    PlanBrief,
    PlanCard,
    PlanSummary,
    PriceBand,
    PricingInfo,
    SceneDist,
    ScheduleItem,
    SellingPoint,
    TrendColor,
    TrendExpression,
    TrendGallery,
    TrendPattern,
    TrendRadar,
    TrendShape,
    TrendSignal,
    UserQuote,
    VoiceTrend,
)
from .planning import (
    PainPoint as PlanningPainPoint,
)
from .pricing import PricePoint, PricingComparison
from .proposal import ProductProposal, ProposalSet, SourceRef
from .recommendation import Decision, ProjectRecommendation
from .retro import DimensionGap, RetroReport
from .review import ConflictRecord, ConflictType, ReviewIssue, ReviewResult
from .scoring import DimensionScore, OpportunityScore, RiskWarning
from .sentiment import PainPoint, SentimentStat, UserSentiment
from .swot import SWOTAnalysis, SWOTItem
from .testcase import BacktestCase, BacktestSet, Outcome

__all__ = [
    "BacktestCase",
    "BacktestSet",
    "Brief",
    "BudgetRange",
    "CategoryRank",
    "ChallengeRecord",
    "ChallengeStance",
    "CompetitiveMap",
    "CompetitorProduct",
    "Confidence",
    "ConflictRecord",
    "ConflictType",
    "ConsumerVoice",
    "CostCheck",
    "CountryPlan",
    "DataBoard",
    "Decision",
    "DimensionGap",
    "DimensionScore",
    "EvidenceLink",
    "EvidenceMixin",
    "EvidenceRef",
    "FeatureMatrix",
    "GTMPlan",
    "GapZone",
    "HeatCurve",
    "HeatCurveSeries",
    "HitProduct",
    "HotProductRank",
    "IPAssessment",
    "IPCandidate",
    "IPPoolItem",
    "InsightBase",
    "InsightBundle",
    "Opportunity",
    "OpportunityScore",
    "Outcome",
    "PainPoint",
    "PlanBrief",
    "PlanCard",
    "PlanSummary",
    "PlanningPainPoint",
    "PriceBand",
    "PricePoint",
    "PricingComparison",
    "PricingInfo",
    "ProductProposal",
    "ProjectRecommendation",
    "ProposalSet",
    "RetroReport",
    "ReviewIssue",
    "ReviewResult",
    "RiskWarning",
    "SWOTAnalysis",
    "SWOTItem",
    "SceneDist",
    "ScheduleItem",
    "SellingPoint",
    "SentimentStat",
    "SourceRef",
    "TrendColor",
    "TrendExpression",
    "TrendGallery",
    "TrendItem",
    "TrendPattern",
    "TrendRadar",
    "TrendShape",
    "TrendSignal",
    "UserQuote",
    "UserSentiment",
    "VoiceTrend",
    "WeightTemplate",
    "Weights",
]
