"""MINISO 内部 IP 资源库 — 代表性 IP 策展数据（12 个）

定位：机会生成 Agent 的弹药库，字段按「Agent 可消费」设计；页面只是数据的可视化皮囊。
图片规范：frontend/public/assets/ip/{slug}/logo.png（透明底 ≥400px）+ cover.jpg（名创联名实拍，横版 ≥800px）
图片缺失时前端自动降级（色块占位），素材后补即生效。
matrix 坐标区间锁定 0~1：x 轴 女性向(0) → 男性/ACG(1)，y 轴 可爱萌系(0) → 潮流个性(1)。
四象限定位为 AI 基于历史商品特征的推演，仅作演示参考，非市场调研数据。

数据来源：自前端 fixtures/ipResource.js 逐字段迁移（策展数据，非 LLM 生成）。
"""

from __future__ import annotations

IP_STATS = [
    {"value": "150+", "label": "全球合作 IP"},
    {"value": "10,000+", "label": "年度 IP 新品"},
    {"value": "800M+", "label": "IP 产品累计销量"},
]

IP_RESOURCE = [
    {
        "slug": "sanrio",
        "name": "Sanrio",
        "nameCn": "三丽鸥",
        "styleTags": ["可爱", "少女", "收藏向"],
        "audienceGroup": "女性向",
        "styleGroup": "可爱萌系",
        "audience": "年轻女性",
        "categories": ["美妆", "香薰", "家居", "毛绒", "数码配件"],
        "characters": ["Hello Kitty", "Kuromi", "My Melody", "Cinnamoroll"],
        "designAssets": ["蝴蝶结", "粉紫配色", "圆润造型", "表情化"],
        "potential": 5,
        "minisoHistory": "名创长期核心合作 IP，联名覆盖全品类，女性客群基本盘",
        "matrix": {"x": 0.15, "y": 0.18},
    },
    {
        "slug": "disney",
        "name": "Disney",
        "nameCn": "迪士尼",
        "styleTags": ["经典", "全年龄", "故事性"],
        "audienceGroup": "大众",
        "styleGroup": "大众经典",
        "audience": "大众家庭 / 全年龄",
        "categories": ["家居", "玩具", "数码", "生活方式"],
        "characters": ["Mickey", "Stitch", "Lotso", "Winnie the Pooh"],
        "designAssets": ["线稿角色", "波点元素", "经典红白黑", "角色叙事"],
        "potential": 5,
        "minisoHistory": "名创最重要的长期合作伙伴之一，米奇/草莓熊/史迪奇多线联名",
        "matrix": {"x": 0.42, "y": 0.45},
    },
    {
        "slug": "chiikawa",
        "name": "Chiikawa",
        "nameCn": "吉伊卡哇",
        "styleTags": ["治愈", "可爱", "收藏向"],
        "audienceGroup": "女性向",
        "styleGroup": "可爱萌系",
        "audience": "年轻女性 / Z世代",
        "categories": ["毛绒", "桌面摆件", "文具", "小风扇"],
        "characters": ["Chiikawa", "Hachiware", "Usagi"],
        "designAssets": ["圆润线条", "低饱和奶油色", "表情化", "小体积适配"],
        "potential": 5,
        "minisoHistory": "2023 年合作后迅速成为全国性爆款，社媒热度持续走高",
        "matrix": {"x": 0.22, "y": 0.30},
    },
    {
        "slug": "harry-potter",
        "name": "Harry Potter",
        "nameCn": "哈利·波特",
        "styleTags": ["魔法", "情怀", "复古"],
        "audienceGroup": "大众",
        "styleGroup": "潮流个性",
        "audience": "全年龄 / 粉丝向",
        "categories": ["家居", "文具", "服饰配件", "香薰"],
        "characters": ["四大学院", "Hedwig", "金色飞贼"],
        "designAssets": ["学院纹章", "深色调", "复古字体", "金属配件"],
        "potential": 4,
        "minisoHistory": "名创 Super IP 体系重点 IP，粉丝客群消费力强",
        "matrix": {"x": 0.60, "y": 0.72},
    },
    {
        "slug": "barbie",
        "name": "Barbie",
        "nameCn": "芭比",
        "styleTags": ["时尚", "自信", "粉色经济"],
        "audienceGroup": "女性向",
        "styleGroup": "潮流个性",
        "audience": "年轻女性",
        "categories": ["美妆", "香薰", "配饰", "生活方式"],
        "characters": ["Barbie", "Ken"],
        "designAssets": ["芭比粉", "复古美式", "亮片元素"],
        "potential": 4,
        "minisoHistory": "电影热映带动粉色经济，年轻女性时尚联名首选",
        "matrix": {"x": 0.25, "y": 0.80},
    },
    {
        "slug": "snoopy",
        "name": "Snoopy / PEANUTS",
        "nameCn": "史努比",
        "styleTags": ["经典", "治愈", "美式复古"],
        "audienceGroup": "大众",
        "styleGroup": "大众经典",
        "audience": "大众 / 家庭",
        "categories": ["家居", "户外", "文具", "服饰"],
        "characters": ["Snoopy", "Woodstock", "Charlie Brown"],
        "designAssets": ["美式漫画线稿", "红白配色", "复古字体"],
        "potential": 4,
        "minisoHistory": "名创长期合作 IP，生活方式与家居品类常客",
        "matrix": {"x": 0.52, "y": 0.38},
    },
    {
        "slug": "one-piece",
        "name": "One Piece",
        "nameCn": "航海王",
        "styleTags": ["热血", "冒险", "ACG"],
        "audienceGroup": "男性向",
        "styleGroup": "潮流个性",
        "audience": "男性 / ACG 人群",
        "categories": ["手办摆件", "服饰", "数码配件"],
        "characters": ["Luffy", "Zoro", "Chopper"],
        "designAssets": ["骷髅旗符号", "高饱和撞色", "漫画分镜"],
        "potential": 4,
        "minisoHistory": "官网 Super IP 在列，ACG 人群引流担当",
        "matrix": {"x": 0.85, "y": 0.72},
    },
    {
        "slug": "bt21",
        "name": "BT21",
        "nameCn": "BT21（BTS 联名）",
        "styleTags": ["潮流", "K-pop", "收藏向"],
        "audienceGroup": "女性向",
        "styleGroup": "潮流个性",
        "audience": "Z世代 / 粉丝群体",
        "categories": ["毛绒", "数码配件", "文具", "家居"],
        "characters": ["Koya", "RJ", "Tata", "Cooky"],
        "designAssets": ["扁平几何", "高饱和单色", "表情包化"],
        "potential": 4,
        "minisoHistory": "名创 IP 店与海外门店大量在售，粉丝经济典型样本",
        "matrix": {"x": 0.62, "y": 0.60},
    },
    {
        "slug": "marvel",
        "name": "Marvel",
        "nameCn": "漫威",
        "styleTags": ["英雄", "潮流", "力量感"],
        "audienceGroup": "男性向",
        "styleGroup": "潮流个性",
        "audience": "男性 / 大众",
        "categories": ["数码配件", "服饰", "手办摆件", "家居"],
        "characters": ["Spider-Man", "Iron Man", "Captain America"],
        "designAssets": ["红黑撞色", "金属质感", "符号化 Logo"],
        "potential": 4,
        "minisoHistory": "曾合作推出 2000+ 超级英雄周边产品",
        "matrix": {"x": 0.88, "y": 0.85},
    },
    {
        "slug": "pokemon",
        "name": "Pokémon",
        "nameCn": "宝可梦",
        "styleTags": ["ACG", "收藏", "全年龄"],
        "audienceGroup": "大众",
        "styleGroup": "可爱萌系",
        "audience": "大众 / ACG 人群",
        "categories": ["毛绒", "数码配件", "文具", "家居"],
        "characters": ["Pikachu", "Eevee", "Snorlax"],
        "designAssets": ["明黄色", "圆润轮廓", "图鉴收集机制"],
        "potential": 5,
        "minisoHistory": "官方门店资料在列，皮卡丘国民认知度极高",
        "matrix": {"x": 0.60, "y": 0.42},
    },
    {
        "slug": "minions",
        "name": "Minions",
        "nameCn": "小黄人",
        "styleTags": ["搞笑", "全年龄", "萌贱"],
        "audienceGroup": "大众",
        "styleGroup": "大众经典",
        "audience": "大众家庭 / 亲子",
        "categories": ["玩具", "家居", "文具"],
        "characters": ["Kevin", "Stuart", "Bob"],
        "designAssets": ["明黄+牛仔蓝", "胶囊造型", "表情化"],
        "potential": 4,
        "minisoHistory": "照明娱乐当家 IP，亲子客群稳定基本盘",
        "matrix": {"x": 0.48, "y": 0.42},
    },
    {
        "slug": "we-bare-bears",
        "name": "We Bare Bears",
        "nameCn": "咱们裸熊",
        "styleTags": ["治愈", "日常", "简约"],
        "audienceGroup": "大众",
        "styleGroup": "可爱萌系",
        "audience": "年轻大众",
        "categories": ["家居", "毛绒", "文具", "服饰"],
        "characters": ["Grizzly", "Panda", "Ice Bear"],
        "designAssets": ["极简色块", "日常场景叙事", "低饱和配色"],
        "potential": 3,
        "minisoHistory": "Cartoon Network 经典 IP，简约风适配名创设计语言",
        "matrix": {"x": 0.55, "y": 0.28},
    },
]

# 筛选维度（前端 Segmented 用）
AUDIENCE_FILTERS = ["全部", "女性向", "大众", "男性向"]
STYLE_FILTERS = ["全部", "可爱萌系", "大众经典", "潮流个性"]
